### ISSUE TITLE
zonal mean 3D variable trying to use a DASK array

### ISSUE THREAD

**Issue by bitterbark** [NCAR/ADF#112]
### ADF run type

Model vs. Model

### What happened?

 Generating zonal mean plots...
NOTE: Plot type is set to png
	 ⌛ zonal mean plots for SWCF
	 ⌛ zonal mean plots for LWCF
	 ⌛ zonal mean plots for PSL
	 ⌛ zonal mean plots for Q
Q has lev dimension.
...

Traceback (most recent call last):
  File "/glade/u/apps/opt/conda/envs/npl/lib/python3.7/site-packages/xarray/core/ops.py", line 190, in _call_possibly_missing_method
    method = getattr(arg, name)
AttributeError: 'Array' object has no attribute 'item'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./run_adf_diag", line 175, in <module>
    diag.create_plots()
  File "/glade/u/home/bundy/cam/diag/ADF_top/ADF/lib/adf_diag.py", line 844, in create_plots
    log_section = "create_plots")
  File "/glade/u/home/bundy/cam/diag/ADF_top/ADF/lib/adf_diag.py", line 435, in __diag_scripts_caller
    module_name=func_name)
  File "/glade/u/home/bundy/cam/diag/ADF_top/ADF/lib/adf_diag.py", line 468, in __function_caller
    return func(self)
  File "/glade/u/home/bundy/cam/diag/ADF_top/ADF/lib/../scripts/plotting/zonal_mean.py", line 248, in zonal_mean
    oseasons[s], ops_season, ohya, ohyb, **vres)
  File "/glade/u/home/bundy/cam/diag/ADF_top/ADF/lib/plotting_functions.py", line 550, in plot_zonal_mean_and_save
    diffnorm = normfunc(vmin=min(np.min(diff),-1*np.max(diff)), vcenter=0.0, vmax=np.max(diff))
  File "/glade/u/apps/opt/conda/envs/npl/lib/python3.7/site-packages/matplotlib/colors.py", line 1324, in __init__
    super().__init__(vmin=vmin, vmax=vmax)
  File "/glade/u/apps/opt/conda/envs/npl/lib/python3.7/site-packages/matplotlib/colors.py", line 1135, in __init__
    self._vmin = _sanitize_extrema(vmin)
  File "/glade/u/apps/opt/conda/envs/npl/lib/python3.7/site-packages/matplotlib/colors.py", line 100, in _sanitize_extrema
    ret = ex.item()
  File "/glade/u/apps/opt/conda/envs/npl/lib/python3.7/site-packages/xarray/core/ops.py", line 202, in func
    return _call_possibly_missing_method(self.data, name, args, kwargs)
  File "/glade/u/apps/opt/conda/envs/npl/lib/python3.7/site-packages/xarray/core/ops.py", line 192, in _call_possibly_missing_method
    duck_array_ops.fail_on_dask_array_input(arg, func_name=name)
  File "/glade/u/apps/opt/conda/envs/npl/lib/python3.7/site-packages/xarray/core/duck_array_ops.py", line 65, in fail_on_dask_array_input
    raise NotImplementedError(msg % func_name)
NotImplementedError: 'item' is not yet a valid method on dask arrays
114.032u 8.277s 2:50.97 71.5%	0+0k 8+0io 0pf+0w

### ADF Hash you are using

187c929

### What machine were you running the ADF on?

CISL machine

### What python environment were you using?

NPL (CISL machines only)

### Extra info

Brian told me this needs to change to a numpy array. Happy to do that if I can find an example.

**Comment by brianpm** [comment]
Ah, this is not actually as much my fault as I thought! This error is happening when we try to set the color normalization. Inside matplotlib, it tries to "sanitize" the values that get used (https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/colors.py). It looks like they assume a numpy array, so use `item` to get a scalar. In our case, for some reason a dask array is being used, so we need to call `compute` on it before using it in the color normalization function.
