### ISSUE TITLE
Website will not be created if only creating tables

### ISSUE THREAD

**Issue by cecilehannay** [NCAR/ADF#194]
### ADF run type

Model vs. Model

### What happened?

The website will not be created if only creating tables (and no plots)

Here is the error I am getting.

----- 

The analysis_scripts and plotting_scripts in my config_file is set to: 
```
#List of analysis scripts being used.
#These scripts must be located in "scripts/analysis":
analysis_scripts:
    - amwg_table

#List of plotting scripts being used.
#These scripts must be located in "scripts/plotting":
plotting_scripts:
    #- global_latlon_map
    #- global_latlon_vect_map
    #- zonal_mean
    #- polar_map
    #- cam_taylor_diagram
    #- qbo 
```

The error is: 
```
Generating Diagnostics webpages...
Traceback (most recent call last):
  File "./run_adf_diag", line 190, in <module>
    diag.create_website()
  File "/glade/work/hannay/ADF/ADF/lib/adf_diag.py", line 1112, in create_website
    ptype_html = sorted([ptype_html_dict[x] for x in plot_func_names if x in ptype_html_dict])
TypeError: 'NoneType' object is not iterable
```

### ADF Hash you are using

682c95b

### What machine were you running the ADF on?

CISL machine

### What python environment were you using?

NPL (CISL machines only)

### Extra info

None

**Comment by cecilehannay** [comment]
This is the error I am getting.

The analysis_scripts and plotting_scripts in my config_file is set to: 
```
#List of analysis scripts being used.
#These scripts must be located in "scripts/analysis":
analysis_scripts:
    - amwg_table

#List of plotting scripts being used.
#These scripts must be located in "scripts/plotting":
plotting_scripts:
    #- global_latlon_map
    #- global_latlon_vect_map
    #- zonal_mean
    #- polar_map
    #- cam_taylor_diagram
    #- qbo 
```

The error is: 
```
Generating Diagnostics webpages...
Traceback (most recent call last):
  File "./run_adf_diag", line 190, in <module>
    diag.create_website()
  File "/glade/work/hannay/ADF/ADF/lib/adf_diag.py", line 1112, in create_website
    ptype_html = sorted([ptype_html_dict[x] for x in plot_func_names if x in ptype_html_dict])
TypeError: 'NoneType' object is not iterable
```
