### ISSUE TITLE
Turn off climo file generation (for non-h0 files that won't be used)

### ISSUE THREAD

**Issue by bitterbark** [NCAR/ADF#299]
### New feature type

New infrastructure or infrastructure enhancement

### What is this new feature?

In the config.yml, when we comment out `time_averaging_scripts: create_climo_files` it fails. (Will will reply with the error).
It would be great for the non-h0/MDTF applications if we didn't have to wait while it makes climo files that won't be used.

### Assistance required?

Yes, I will need some assistance before making a PR

**Comment by WillyChap** [comment]
Here is the Traceback error when time_averaging_scripts are turned off: 


`Traceback (most recent call last):
  File "/glade/work/wchapman/ADF_dani/./run_adf_diag", line 167, in <module>
    diag.create_climo()
  File "/glade/work/wchapman/ADF_dani/lib/adf_diag.py", line 730, in create_climo
    self.end_diag_fail(emsg)
  File "/glade/work/wchapman/ADF_dani/lib/adf_base.py", line 83, in end_diag_fail
    raise AdfError(msg)
adf_base.AdfError: No time_averaging_scripts provided for calculating climatologies, but climatologies were requested.
Please either provide a valid averaging script, or skip the calculation of climatologies. `
