### ISSUE TITLE
Plotting error when running with specific humidity (Q)

### ISSUE THREAD

**Issue by nusbaume** [NCAR/ADF#38]
Both @juliecaron and @andrewgettelman have received the following error when running the diagnostics with the variable Q (specific humidity):

```
Q has lev dimension.

Traceback (most recent call last):

  File "./run_diag", line 178, in <module>

    diag.create_plots()

  File "/glade/campaign/cgd/amp/jcaron/python/CAM_diagnostics/lib/CamDiag.py", line 1028, in create_plots

    function_caller(plot_func_name, plot_func_args, func_kwargs=plot_func_kwargs, module_name=plot_func_name+'.py')

  File "/glade/campaign/cgd/amp/jcaron/python/CAM_diagnostics/lib/CamDiag.py", line 175, in function_caller

    return func(*func_args, **func_kwargs)

  File "/glade/campaign/cgd/amp/jcaron/python/CAM_diagnostics/lib/../scripts/plotting/zonal_mean.py", line 183, in zonal_mean

    oseasons[s], ops_season, ohya, ohyb)

  File "/glade/campaign/cgd/amp/jcaron/python/CAM_diagnostics/lib/plotting_functions.py", line 330, in plot_zonal_mean_and_save

    diffnorm = normfunc(vmin=np.min(diff), vcenter=0.0, vmax=np.max(diff))

  File "/glade/u/apps/dav/opt/python/3.7.9/gnu/9.1.0/pkg-library/20201220/lib/python3.7/site-packages/matplotlib/colors.py", line 1136, in __init__

    raise ValueError('vmin, vcenter, and vmax must be in '

ValueError: vmin, vcenter, and vmax must be in ascending order
```

This is very likely a bug, and thus should be fixed accordingly.

**Comment by brianpm** [comment]
Ah! This is raising a ValueError because min(diff) > 0. I thought I had put in logic to catch that case. In the absence of using some kind of default color levels, there are a couple options. To keep using the diverging colormap, I would recommend just making vmin=min(min(diff),-1*max(diff)); i.e., just a symmetric colormap, and the lower half won't be used in the plot.

**Comment by nusbaume** [comment]
Great, thanks for finding the fix @brianpm!  I can include this fix in my own development work, unless you or @bitterbark want to take a stab at it?
